//create empty variables for each month to hold the strings of quotes
var janQuotes = [
["1876", "Native Americans", "The United States ordered all Native Americans to move into reservations."],
["1953", "NBA Baltimore Bullets players", 'The Baltimore Bullets began a 32 game road losing streak.'],
["1990", "Manuel Antonio Noriega", "After holing up for 10 days at the Vatican embassy in Panama City, General Manuel Noriega surrenders to U.S. troops to face charges of drug trafficking."],
["1974", "President Richard Nixon", "President Richard Nixon refuses to hand over tape recordings and documents that had been subpoenaed by the Senate Watergate Committee. Marking the beginning of the end of his Presidency, Nixon would resign from office in disgrace eight months later."],
["1643", "The institute of marriage", "In the first record of a legal divorce in the American colonies, Anne Clarke of the Massachusetts Bay Colony is granted a divorce from her absent and adulterous husband, Denis Clarke, by the Quarter Court of Boston, Massachusetts."],
["1838", "The smoke signal", "On this day in 1838, Samuel Morse's telegraph system is demonstrated for the first time at the Speedwell Iron Works in Morristown, New Jersey. The telegraph, a device which used electric impulses to transmit encoded messages over a wire, would eventually revolutionize long-distance communication, reaching the height of its popularity in the 1920s and 1930s."],
["1999", "Bill Clinton", "On January 7, 1999, the impeachment trial of President Bill Clinton, formally charged with lying under oath and obstructing justice, begins in the Senate. As instructed in Article 1 of the U.S. Constitution, Supreme Court Chief Justice William Rehnquist was sworn in to preside, and the senators were sworn in as jurors."],
["2000", "Buffalo Bills fans", "In an American Football Conference (AFC) wild card match-up at Adelphia Coliseum in Nashville, Tennessee, the Tennessee Titans stage a last-second come-from-behind victory to beat the Buffalo Bills 22-16 on a kickoff return play later dubbed the \"Music City Miracle.\""],
["2007", "The flip style cell phone", "Apple Inc. CEO Steve Jobs unveils the iPhone—a touchscreen mobile phone with an iPod, camera and Web-browsing capabilities, among other features—at the Macworld convention in San Francisco."],
["1982", "Dallas Cowboy fans", "San Francisco 49ers wide receiver Dwight Clark makes a leaping catch in the end zone on a pass from quarterback Joe Montana with 51 seconds left in the National Football Conference (NFC) championship game against the Dallas Cowboys. \"The Catch\" set up a successful extra point kick by Ray Wersching that lifted the 49ers to a 28-27 victory and a trip to Super Bowl XVI."],
["1927", "Charlie Chaplin", "Charlie Chaplin’s $16 million estate is frozen by court receivers after his second wife, Lita Grey Chaplin, sues for divorce."],
["1991", "Saddam Hussein", "The U.S. Congress gives the green light to military action against Iraq in the Persian Gulf Crisis."],
["1919", "Alcohol", "California votes to ratify the prohibition amendment."],
["1526", "Francis of France", "After being held captive by Charles V for a year, signs the Treaty of Madrid, giving up most of his claims in France and Italy."],
["2001", "Encyclopedia salespersons", "Wikipedia goes online."],
["600", "The phrase gesundheit", "Pope Gregory the Great decreea saying \"God bless You\" is the correct response to a sneeze."],
["1950", "Brinks armored cars company", "11 men steal more than $2 million from the Brinks Armored Car depot in Boston, Massachusetts."],
["1990", "Mayor Marion Barry", "At the end of a joint sting operation by FBI agents and District of Columbia police, Mayor Marion Barry is arrested and charged with drug possession and the use of crack, a crystalline form of cocaine"],
["2007", "Chinese diet", "Beijing, China, the capital city of the planet's most populous nation, gets its first drive-through McDonald's restaurant."],
["1863", "Genreal Burnside", "Union General Ambrose Burnside's Army of the Potomac begins an offensive against General Robert E. Lee's Army of Northern Virginia that quickly bogs down as several days of heavy rain turn the roads of Virginia into a muddy quagmire. The campaign was abandoned three days later."],
["1950", "Alger Hiss", "In the conclusion to one of the most spectacular trials in U.S. history, former State Department official Alger Hiss is convicted of perjury. He was convicted of having perjured himself in regards to testimony about his alleged involvement in a Soviet spy ring before and during World War II."],
["1807", "Aaron Burr", "President Thomas Jefferson exposes a plot by Aaron Burr to form a new republic in the Southwest."],
["1965", "Bill Russell", "Boston Celtic center Bill Russell misses all 14 shots in loss to Philadelphia Warriors led by Wilt Chamberlain"],
["41", "Caligula", "Shortly after declaring himself a god, Caligula is assassinated by two Praetorian tribunes."],
["1915", "The mailed letter", "Alexander Graham Bell in New York and Thomas Watson in San Francisco make a record telephone transmission."],
["1967", "Chicago citizens", "Chicago Blizzard strikes with a record 23 inches of snow fall causing 800 buses and 50,000 automobiles to be abandoned."],
["1984", "Michael Jackson", "His hair catches fire and he is burned during a commercial filming for Pepsi."],
["1871", "The French Army","Surrounded by Prussian troops and suffering from famine, the French army in Paris surrenders. During the siege, balloons were used to keep contact with the outside world."],
["1978", "Big Hair", "Sweden outlaws aerosol sprays due to their harmful effect on the ozone layer, becoming the first nation to enact such a ban."],
["1798", "Roger Griswold", "Rep Matthew Lyon (Vt) spits in face of Rep Roger Griswold (Ct) in US House of Representatives, after an argument."],
["1871", "Sunbathers in San Fransisco", "Millions of birds fly over western SF, darkening the sky."]
],

febQuotes = [
["1906", "Criminals", "The 1st federal penitentiary building was completed in Leavenworth, Kansas."],
["1992", "Willie Nelson", "Willie Nelson settles with the IRS for 9 million dollars."],
["1690", "Coins", "The first paper money in America is issued in the Massachusetts Bay Colony."],
["1971", "Rich English guys", "The British car maker Rolls Royce declared itself bankrupt."],
["1988", "Evan Mecham", "Arizona House of Reps vote to impeach Republican Gov Evan Mecham."],
["1951", "Paul Harvey", "Radio commentator Paul Harvey arrested for trying to sneak into Argonne National Laboratory, a nuclear test site located 20 miles west of Chicago."],
["1990", "South Torrance HS basketball team", "Lisa Leslie of Morningside HS in Inglewood California scores 101 in 1st half, South Torrance HS decides not to play 2nd half & loses 102-24."],
["1926", "Roy Disney", "Disney Brothers Cartoon Studio becomes Walt Disney Studios."],
["1891", "Kids in San Fransisco", "The first shipment of asparagus arrives in San Fransisco"],
["1996", "Gary Kasparov", "After three hours, world chess champion Gary Kasparov loses the first game of a six-game match against Deep Blue, an IBM computer capable of evaluating 200 million moves per second."],
["1960", "Radio Stations", "The Payola scandal reaches a new level of public prominence and legal gravity on this day in 1960, when President Eisenhower called it an issue of public morality and the FCC proposed a new law making involvement in Payola a criminal act."],
["2008", "GM","In an attempt to cut costs, struggling auto giant General Motors (GM) offers buyouts to all 74,000 of its hourly employees in the U.S. represented by the United Auto Workers (UAW) union. The move came after GM lost $38.7 billion in 2007, which at the time was the largest loss ever experienced by any car maker."],
["1633", "Galileo", "Italian philosopher, astronomer and mathematician Galileo Galilei arrives in Rome to face charges of heresy for advocating Copernican theory, which holds that the Earth revolves around the Sun."],
["278", "St. Valentine", "Valentine, a holy priest in Rome in the days of Emperor Claudius II, was executed."],
["1898", "The USS Maine", "A massive explosion of unknown origin sinks the battleship USS Maine in Cuba's Havana harbor."],
["1923", "King Tut's Remains", "In Thebes, Egypt, English archaeologist Howard Carter enters the sealed burial chamber of the ancient Egyptian ruler King Tutankhamen."],
["1928", "Productivity", "The first color television is demonstrated at the Dominion Theatre in London."],
["2001", "Robert Hanssen", "FBI agent Robert Hanssen is arrested for spying for the Soviet Union. He was ultimately convicted and sentenced to life in prison."],
["1807", "Aaron Burr", "VP Aaron Burr arrested in Alabama for treason."],
["1985", "unplanned pregnancy", "In a highly controversial vote, the Irish government defies the powerful Catholic Church and approves the sale of contraceptives"],
["1994", "Aldrich Ames", "CIA operative Aldrich Ames is arrested for selling secrets to the Soviet Union."],
["1980", "Russian hockey", "In one of the most dramatic upsets in Olympic history, the underdog U.S. hockey team, made up of college players, defeats the four-time defending gold-medal winning Soviet team at the XIII Olympic Winter Games in Lake Placid, New York."],
["1958", "Juan Manuel Fangio", "Five-time Formula One champion Juan Manuel Fangio of Argentina is kidnapped in Cuba by a group of Fidel Castro's rebels."],
["1868", "Andrew Johnson", "The U.S. House of Representatives votes 11 articles of impeachment against President Andrew Johnson, nine of which cite Johnson's removal of Secretary of War Edwin M. Stanton, a violation of the Tenure of Office Act. The House vote made President Johnson the first president to be impeached in U.S. history."],
["1779", "British Forces", "Fort Sackville is surrendered, marking the beginning of the end of British domination in America's western frontier."],
["1982", "Rev Jesse Jackson", "Acknowledges that he called NYC \"Hymietown\""],
["2003", "Biljana Plavsic", "Former Bosnian Serb leader Biljana Plavsic is sentenced by the U.N. tribunal in The Hague, Netherlands, to 11 years in prison."],
["1989", "Brian Gumbel", "Letter by Brian Gumbel cirticizing Today Show co-workers becomes public."]
],

marQuotes = [
["1932", "The Lindbergh Family", "In a crime that captured the attention of the entire nation, Charles Lindbergh III, the 20-month-old son of aviation hero Charles Lindbergh, is kidnapped from the family's new mansion in Hopewell, New Jersey."],
["1978", "Charlie Chaplin's Corpse", "n one of history’s most famous cases of body-snatching, two men steal the corpse of the revered film actor Sir Charles Chaplin from a cemetery in the Swiss village of Corsier-sur-Vevey, located in the hills above Lake Geneva, near Lausanne, Switzerland."],
["1845", "John Tyler", "Congress reins in President John Tyler's zealous use of the presidential veto, overriding it with the necessary two-thirds vote. This marked Congress' first use of the Consitutional provision allowing Congressional veto overrides and represented Congress' parting gift to Tyler as he left office."],
["1987", "Ronald Reagan", "President Reagan takes full responsibility for the Iran-Contra affair in a national address."],
["1969", "Jim Mirrison", "The Dade County Sheriff's Office issues an arrest warrant for Doors' lead singer Jim Morrison. He is charged with a single felony count and three misdemeanors for his stage antics at a Miami concert a few days earlier."],
["1899", "Headaches", "The Imperial Patent Office in Berlin registers Aspirin, the brand name for acetylsalicylic acid, on behalf of the German pharmaceutical company Friedrich Bayer & Co."],
["1876", "Telegrams", "29-year-old Alexander Graham Bell receives a patent for his revolutionary new invention-the telephone."],
["1993", "Music Videos", "The Music Television Network (MTV) airs the first episode of the animated series Beavis and Butthead, which will go on to become the network’s highest-rated series up to that point."],
["1562", "Love", "Kissing in public is banned in Naples and is punishable by death."],
["1963", "The guy guarding Wilt Chamberlain", "Wilt Chamberlain of NBA SF Warriors scores 70 points vs Syracuse."],
["1969", "Fashion", "Levi-Strauss starts to sell bell-bottomed jeans."],
["1963", "The guy guarding Wilt Chamberlain", "Wilt Chamberlain of NBA SF Warriors scores 70 points vs Syracuse."],
["1969", "Fashion", "Levi-Strauss starts to sell bell-bottomed jeans."],
["1876", "Telegrams", "29-year-old Alexander Graham Bell receives a patent for his revolutionary new invention-the telephone."],
["1932", "The Lindbergh Family", "In a crime that captured the attention of the entire nation, Charles Lindbergh III, the 20-month-old son of aviation hero Charles Lindbergh, is kidnapped from the family's new mansion in Hopewell, New Jersey."],
["1978", "Charlie Chaplin's Corpse", "n one of history’s most famous cases of body-snatching, two men steal the corpse of the revered film actor Sir Charles Chaplin from a cemetery in the Swiss village of Corsier-sur-Vevey, located in the hills above Lake Geneva, near Lausanne, Switzerland."],
["1845", "John Tyler", "Congress reins in President John Tyler's zealous use of the presidential veto, overriding it with the necessary two-thirds vote. This marked Congress' first use of the Consitutional provision allowing Congressional veto overrides and represented Congress' parting gift to Tyler as he left office."],
["1987", "Ronald Reagan", "President Reagan takes full responsibility for the Iran-Contra affair in a national address."],
["1969", "Jim Mirrison", "The Dade County Sheriff's Office issues an arrest warrant for Doors' lead singer Jim Morrison. He is charged with a single felony count and three misdemeanors for his stage antics at a Miami concert a few days earlier."],
["1899", "Headaches", "The Imperial Patent Office in Berlin registers Aspirin, the brand name for acetylsalicylic acid, on behalf of the German pharmaceutical company Friedrich Bayer & Co."],
["1876", "Telegrams", "29-year-old Alexander Graham Bell receives a patent for his revolutionary new invention-the telephone."],
["1932", "The Lindbergh Family", "In a crime that captured the attention of the entire nation, Charles Lindbergh III, the 20-month-old son of aviation hero Charles Lindbergh, is kidnapped from the family's new mansion in Hopewell, New Jersey."],
["1978", "Charlie Chaplin's Corpse", "n one of history’s most famous cases of body-snatching, two men steal the corpse of the revered film actor Sir Charles Chaplin from a cemetery in the Swiss village of Corsier-sur-Vevey, located in the hills above Lake Geneva, near Lausanne, Switzerland."],
["1845", "John Tyler", "Congress reins in President John Tyler's zealous use of the presidential veto, overriding it with the necessary two-thirds vote. This marked Congress' first use of the Consitutional provision allowing Congressional veto overrides and represented Congress' parting gift to Tyler as he left office."],
["1987", "Ronald Reagan", "President Reagan takes full responsibility for the Iran-Contra affair in a national address."],
["1969", "Jim Mirrison", "The Dade County Sheriff's Office issues an arrest warrant for Doors' lead singer Jim Morrison. He is charged with a single felony count and three misdemeanors for his stage antics at a Miami concert a few days earlier."],
["1899", "Headaches", "The Imperial Patent Office in Berlin registers Aspirin, the brand name for acetylsalicylic acid, on behalf of the German pharmaceutical company Friedrich Bayer & Co."],
["1876", "Telegrams", "29-year-old Alexander Graham Bell receives a patent for his revolutionary new invention-the telephone."],
["1876", "Telegrams", "29-year-old Alexander Graham Bell receives a patent for his revolutionary new invention-the telephone."],
["1987", "Ronald Reagan", "President Reagan takes full responsibility for the Iran-Contra affair in a national address."],
["2008", "Aloha Airlines","They went bankrupt and permanently ended passenger service."]
],

aprQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

mayQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

junQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

julQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

augQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
//13//
["1961", "the people of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
//14//
["1901", "sailors on the S.S. Islander", "when their ship hit an iceberg near Alaska and sinks!"],
//15//
["1040", "King Duncan I", "Duncan, King of the Scots is killed in battle against his first cousin and rival Macbeth. The latter succeeds him for the throne."],
//16//
["1988", "New York character", "Mayor Koch vows to wip out street vendors, panhandlers and windshield washers."],
//17//
["1957", "Alice Roth", "Philadelphia Phillies player, Richie Ashburn fouls a ball that hits Alice Roth twice in the same at bat. The first foul broke her nose, and the second foul hits her while leaving on a stretcher."],
//18//
["1591", "John White", "Governor, John White, of Roanoke Island colony returned from a three year trip to England to find that everyone in his colony, including his daughter and granddaughter, had disappeared."],
//19//
["1995", "Shannon Faulkner","Shannon was the first woman to attend the Citadel military college in Charleston, SC. After four hours of the military indoctrination training, she spent the remainder of the first week in the infirmary before voluntarily resigning, citing emotional and psychological abuse and physical exhaustion. After her departure, the male cadets openly celebrated on the campus"],
//20//
["1619", "these men", "The first Black slaves were brought to the colony of Jamestown, Virginia by the Dutch."],
//21//
["1841", "Peeping Toms", "John Hampton patents venetian blinds."],
//22//
["1911", "security guards at the Louvre", "The Mona Lisa was stolen from the Louvre by Vincenzo Perugia"],
//23//
["2011", "Muammar al-Gaddafi", "The Libyan leader is overthrown after the National Transitional Council forces take countrol of Bab al-Azizia compound during the 2011 Libyan Civil War."],
//24//
["1961", "justice", "Former Nazi leadier Johannes Voster becomes South Africa's minister of justice."],
//25//
["1814", "bibliophiles", "British forces destroy the Librarry of Congress containing 3,000 books."],
//26//
["2013", "higher education", "25,000 applicants to the University of Liberia failed their university entrance emaination."],
//27//
["1859", "the Earth", "The first successful oil well was drilled. near Titusville, Pennsylvania by Edwin Drake."],
//28//
["1917", "American women", "Ten suffragist wer arrested while picketing in front of the White House."],
//29//
["1533", "the Incan civilization", "Francisco Pizarro ordered the death of the last Incan King of Peru, Atahualpa."],
//30//
["1979", "presidential dignity", "President Carter was attacked by a rabbit on a canoe trip in Plains, Georgia."],
//31//
["1056", "Macedonian dynasty", "Byzantine Empress Theodora became ill and died suddenly. Without children to succeed the throne, the Macedonian dynasty came to a swift end."]
],

sepQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

octQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

novQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
];

decQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["2014", "Will Gallop", "Lost in Code Wars to Ryan Huber!"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
];
