//create empty variables for each month to hold the strings of quotes
var janQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

febQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

marQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

aprQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

mayQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

junQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

julQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

augQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
//13//
["1961", "the people of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
//14//
["1901", "sailors on the S.S. Islander", "when their ship hit an iceberg near Alaska and sinks!"],
//15//
["1040", "King Duncan I", "Duncan, King of the Scots goes is killed in battle against his frist cousin and rival Macbeth. The latter succeeds him for the throne."],
//16//
["1988", "New York character", "Mayor Koch vows to wip out street vendors, panhandlers and windshield washers."],
//17//
["1957", "Alice Roth", "Philadelphia Phillies player, Richie Ashburn fouls a ball that hits Alice Roth twice in the same at bat. The first foul broke her nose, and the second foul hits her while leaving on a stretcher."],
//18//
["1591", "John White", "Governor, John White, of Roanoke Island colony returned from a three year trip to England to find that everyone in his colony, including his daughter and granddaughter, had disappeared."],
//19//
["1995", "Shannon Faulkner","Shannon was the first woman to attend the Citadel military college in Charleston, SC. After four hours of the military indoctrination training, she spent the remainder of the first week in the infirmary before voluntarily resigning, citing emotional and psychological abuse and physical exhaustion. After her departure, the male cadets openly celebrated on the campus"],
//20//
["1619", "these men", "The first Black slaves were brought to the colony of Jamestown, Virginia by the Dutch."],
//21//
["1841", "Peeping Toms", "John Hampton patents venetian blinds."],
//22//
["1911", "security guards at the Louvre", "The Mona Lisa was stolen from the Louvre by Vincenzo Perugia"],
//23//
["2011", "Muammar al-Gaddafi", "The Libyan leader is overthrown after the National Transitional Council forces take countrol of Bab al-Azizia compound during the 2011 Libyan Civil War."],
//24//
["1961", "justice", "Former Nazi leadier Johannes Voster becomes South Africa's minister of justice."],
//25//
["1814", "bibliophiles", "British forces destroy the Librarry of Congress containing 3,000 books."],
//26//
["2013", "higher education", "25,000 applicants to the University of Liberia failed their university entrance emaination."],
//27//
["1859", "the Earth", "The first successful oil well was drilled. near Titusville, Pennsylvania by Edwin Drake."],
//28//
["1917", "American women", "Ten suffragist wer arrested while picketing in front of the White House."],
//29//
["1533", "the Incan civilization", "Francisco Pizarro ordered the death of the last Incan King of Peru, Atahualpa."],
//30//
["1979", "presidential dignity", "President Carter was attacked by a rabbit on a canoe trip in Plains, Georgia."],
//31//
["1056", "Macedonian dynasty", "Byzantine Empress Theodora became ill and died suddenly. Without children to succeed the throne, the Macedonian dynasty came to a swift end."]
],

sepQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

octQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

novQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
];

decQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
];
