//create empty variables for each month to hold the strings of quotes
var janQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

febQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

marQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

aprQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

mayQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

junQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

julQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

augQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

sepQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

octQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
],

novQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
];

decQuotes = [
["Day 1"],
["Day 2"],
["Day 3"],
["Day 4"],
["Day 5"],
["Day 6"],
["Day 7"],
["Day 8"],
["Day 9"],
["Day 10"],
["Day 11"],
["Day 12"],
["1961", "People of Berlin", "Berlin was divided as East Germany sealed off the border between the city's eastern and western sectors in order to halt the flight of refugees."],
["1901", "S.S. Islander", "hits an iceberg near Alaska and sinks!"],
["Day 15"],
["Day 16"],
["Day 17"],
["Day 18"],
["Day 19"],
["Day 20"],
["Day 21"],
["Day 22"],
["Day 23"],
["Day 24"],
["Day 25"],
["Day 26"],
["Day 27"],
["Day 28"],
["Day 29"],
["Day 30"],
["Day 31"]
];
